.class public final Lperfetto/protos/Ext4;
.super Ljava/lang/Object;
.source "Ext4.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lperfetto/protos/Ext4$Ext4ZeroRangeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ZeroRangeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4WritepagesResultFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4WritepagesResultFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4WritepagesFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4WritepagesFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4WritepageFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4WritepageFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4WriteEndFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4WriteEndFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4WriteBeginFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4WriteBeginFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4UnlinkExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4UnlinkExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4UnlinkEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4UnlinkEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4TruncateExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4TruncateExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4TruncateEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4TruncateEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4TrimExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4TrimExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4TrimAllFreeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4TrimAllFreeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4SyncFsFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4SyncFsFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4RequestInodeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4RequestInodeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4RequestBlocksFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4RequestBlocksFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4RemoveBlocksFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4RemoveBlocksFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ReleasepageFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ReleasepageFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ReadpageFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ReadpageFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ReadBlockBitmapLoadFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ReadBlockBitmapLoadFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4PunchHoleFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4PunchHoleFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4OtherInodeUpdateTimeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4OtherInodeUpdateTimeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MballocPreallocFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MballocPreallocFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MballocFreeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MballocFreeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MballocDiscardFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MballocDiscardFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MballocAllocFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MballocAllocFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbReleaseInodePaFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbReleaseInodePaFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbReleaseGroupPaFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbReleaseGroupPaFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbNewInodePaFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbNewInodePaFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbNewGroupPaFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbNewGroupPaFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbDiscardPreallocationsFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbDiscardPreallocationsFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbBuddyBitmapLoadFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbBuddyBitmapLoadFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MbBitmapLoadFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MbBitmapLoadFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4MarkInodeDirtyFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4MarkInodeDirtyFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4LoadInodeBitmapFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4LoadInodeBitmapFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4LoadInodeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4LoadInodeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4JournalledWriteEndFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4JournalledWriteEndFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4JournalledInvalidatepageFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4JournalledInvalidatepageFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4JournalStartReservedFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4JournalStartReservedFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4JournalStartFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4JournalStartFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4InvalidatepageFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4InvalidatepageFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4InsertRangeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4InsertRangeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4IndMapBlocksExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4IndMapBlocksExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4IndMapBlocksEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4IndMapBlocksEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4GetReservedClusterAllocFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4GetReservedClusterAllocFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4GetImpliedClusterAllocExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4GetImpliedClusterAllocExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4FreeInodeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4FreeInodeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4FreeBlocksFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4FreeBlocksFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ForgetFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ForgetFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4FindDelallocRangeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4FindDelallocRangeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4FallocateExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4FallocateExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4FallocateEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4FallocateEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtShowExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtShowExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtRmLeafFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtRmLeafFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtRmIdxFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtRmIdxFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtRemoveSpaceDoneFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtRemoveSpaceDoneFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtRemoveSpaceFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtRemoveSpaceFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtPutInCacheFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtPutInCacheFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtMapBlocksExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtMapBlocksExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtMapBlocksEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtMapBlocksEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtLoadExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtLoadExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtInCacheFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtInCacheFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtHandleUnwrittenExtentsFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtHandleUnwrittenExtentsFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtConvertToInitializedFastpathFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtConvertToInitializedFastpathFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4ExtConvertToInitializedEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4ExtConvertToInitializedEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EvictInodeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EvictInodeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsShrinkScanExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsShrinkScanExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsShrinkScanEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsShrinkScanEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsShrinkCountFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsShrinkCountFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsShrinkFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsShrinkFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsRemoveExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsRemoveExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsLookupExtentExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsLookupExtentExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsLookupExtentEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsLookupExtentEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsInsertExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsInsertExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsFindDelayedExtentRangeExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsFindDelayedExtentRangeExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsFindDelayedExtentRangeEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsFindDelayedExtentRangeEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4EsCacheExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4EsCacheExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DropInodeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DropInodeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DiscardPreallocationsFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DiscardPreallocationsFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DiscardBlocksFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DiscardBlocksFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DirectIOExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DirectIOExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DirectIOEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DirectIOEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaWritePagesExtentFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaWritePagesExtentFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaWritePagesFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaWritePagesFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaUpdateReserveSpaceFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaUpdateReserveSpaceFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaReserveSpaceFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaReserveSpaceFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaReleaseSpaceFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaReleaseSpaceFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4CollapseRangeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4CollapseRangeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4BeginOrderedTruncateFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4BeginOrderedTruncateFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4AllocateInodeFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4AllocateInodeFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4AllocateBlocksFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4AllocateBlocksFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4AllocDaBlocksFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4AllocDaBlocksFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4SyncFileExitFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4SyncFileExitFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4SyncFileEnterFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4SyncFileEnterFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaWriteEndFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaWriteEndFtraceEventOrBuilder;,
        Lperfetto/protos/Ext4$Ext4DaWriteBeginFtraceEvent;,
        Lperfetto/protos/Ext4$Ext4DaWriteBeginFtraceEventOrBuilder;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    .line 58538
    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .line 7
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V
    .locals 0
    .param p0, "registry"    # Lcom/google/protobuf/ExtensionRegistryLite;

    .line 10
    return-void
.end method
